MODEL:
  TYPE: "fastpredNF_CIF_separate_cond"
  ENCODER_TYPE: "trajectron"
DATA:
  DATASET_NAME: "Pine_Cam2"
  TP:
    PRED_STATE: "state_v"
    ACCEPT_NAN: true
SOLVER:
  USE_SCHEDULER: true
  WEIGHT_DECAY: 0.0
